#!/usr/bin/env sh

export GO_ATOMPUB_DSN="user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB host=$POSTGRES_PORT_5432_TCP_ADDR port=$POSTGRES_PORT_5432_TCP_PORT sslmode=disable"

mkdir -p /opt/vagrant/log
exec /opt/go.atompub/go.atompub >> /opt/vagrant/log/stdout.log 2>&1
